print("Hello, GitHub!")
print("Another line")
print("Hello, world!")
print(f"Hi {Aidin}")
print("Today is a good day!")
print(sum(1))
print("Python is fun!")
print("Learning GitHub commits.")
import math  
print(math.sqrt(16))
print("10 * 10 =", 10 * 10)
print("Keep pushing forward!")
